version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.main:application
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/whatsapp_bot
      - JWT_SECRET_KEY=development-secret-key-do-not-use-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - TWILIO_ACCOUNT_SID=ACfe44f5cbbed573f96f4ebe029402aeea
      - TWILIO_PHONE_NUMBER=+18483603193
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 app.main:application

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
